#!/bin/bash

# setup xcodebuild environment 
    
SCHEME=jules
DEVICEID=BCB94ECD-C8ED-44C2-94A1-11BA11C49F7E
DESTINATION='platform=iOS Simulator,name=iPhone 16,OS=18.4'
BUNDLEPATH=/Users/reinfurt/Library/Developer/Xcode/DerivedData/jules-gwsnmzsxnrhqilgeriwvrtqmxhtd/Build/Products/Debug-iphonesimulator/Jules.app
BUNDLEID=com.o-r-g.jules

# open simulator 
/Applications/Xcode.app/Contents/Developer/Applications/Simulator.app/Contents/MacOS/Simulator -CurrentDeviceUDID $DEVICEID &

# build
xcodebuild -scheme $SCHEME -destination $DESTINATION build; xcrun simctl install $DEVICEID $BUNDLEPATH; xcrun simctl launch $DEVICEID $BUNDLEID
